# Generated by Django 4.1.2 on 2022-11-10 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('prenom', models.CharField(max_length=20, verbose_name='prenom')),
                ('nom', models.CharField(max_length=20, verbose_name='nom')),
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='matricule')),
            ],
            options={
                'db_table': 'Personnel',
            },
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('idquizz', models.AutoField(db_column='idQuizz', primary_key=True, serialize=False)),
                ('nomfichier', models.CharField(db_column='nomFichier', max_length=30)),
                ('urlfichier', models.CharField(db_column='urlFichier', max_length=200)),
            ],
            options={
                'db_table': 'quizz',
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('codesecteur', models.CharField(db_column='codesecteur', max_length=10, primary_key=True, serialize=False)),
                ('nomsecteur', models.CharField(db_column='nomsecteur', max_length=20)),
            ],
            options={
                'db_table': 'secteur',
            },
        ),
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('matricule', models.OneToOneField(db_column='matricule', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaborateur',
            },
        ),
        migrations.CreateModel(
            name='Superuser',
            fields=[
                ('matricule', models.OneToOneField(db_column='matricule', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.BooleanField()),
            ],
            options={
                'db_table': 'superuser',
            },
        ),
        migrations.CreateModel(
            name='Sessionquizz',
            fields=[
                ('idsession', models.AutoField(db_column='idSession', primary_key=True, serialize=False)),
                ('evaluation', models.BooleanField()),
                ('datecreation', models.DateField(db_column='dateCreation')),
                ('dateexpiration', models.DateField(blank=True, db_column='dateExpiration', null=True)),
                ('timer', models.IntegerField(blank=True, null=True)),
                ('idquizz', models.ForeignKey(db_column='idQuizz', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quizz')),
                ('matricule', models.ForeignKey(db_column='matricule', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.superuser')),
            ],
            options={
                'db_table': 'sessionQuizz',
            },
        ),
        migrations.AddField(
            model_name='quizz',
            name='codesecteur',
            field=models.ForeignKey(blank=True, db_column='codesecteur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.secteur'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='codesecteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.secteur'),
        ),
        migrations.AddField(
            model_name='quizz',
            name='matricule',
            field=models.ForeignKey(blank=True, db_column='matricule', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.superuser'),
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('idhisto', models.AutoField(db_column='idHisto', primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('dateparticipation', models.DateField(blank=True, db_column='dateParticipation', null=True)),
                ('idsession', models.ForeignKey(db_column='idSession', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.sessionquizz')),
                ('matricule', models.ForeignKey(db_column='matricule', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.collaborateur')),
            ],
            options={
                'db_table': 'historique',
            },
        ),
    ]
