# Generated by Django 4.1.2 on 2022-11-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='nomfichier',
            field=models.CharField(db_column='nomFichier', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='urlfichier',
            field=models.CharField(db_column='urlFichier', max_length=200, unique=True),
        ),
    ]
