# Generated by Django 4.1.2 on 2022-11-18 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_historique_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionquizz',
            name='idquizz',
            field=models.ForeignKey(db_column='idQuizz', on_delete=django.db.models.deletion.CASCADE, to='quiz.quizz'),
        ),
    ]
