# Generated by Django 4.1.2 on 2022-11-18 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_sessionquizz_idquizz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='idsession',
            field=models.ForeignKey(db_column='idSession', on_delete=django.db.models.deletion.CASCADE, to='quiz.sessionquizz'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='matricule',
            field=models.ForeignKey(db_column='matricule', on_delete=django.db.models.deletion.CASCADE, to='quiz.collaborateur'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='codesecteur',
            field=models.ForeignKey(blank=True, db_column='codesecteur', null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.secteur'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='matricule',
            field=models.ForeignKey(blank=True, db_column='matricule', null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.superuser'),
        ),
    ]
