# Generated by Django 4.1.3 on 2022-11-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='role',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
