# Generated by Django 4.1.3 on 2022-11-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0004_superuser_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historique',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='historique',
            name='idsession',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='codesecteur',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='codesecteur',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='sessionquizz',
            name='idquizz',
        ),
        migrations.RemoveField(
            model_name='sessionquizz',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='superuser',
            name='matricule',
        ),
        migrations.DeleteModel(
            name='Collaborateur',
        ),
        migrations.DeleteModel(
            name='Historique',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='Quizz',
        ),
        migrations.DeleteModel(
            name='Secteur',
        ),
        migrations.DeleteModel(
            name='Sessionquizz',
        ),
        migrations.DeleteModel(
            name='Superuser',
        ),
    ]
